export default [
	"Why don't skeletons fight each other?",
	"What do you call fake spaghetti?",
	"Why did the scarecrow win a award?",
	"How does a penguin build its house?",
	"What did one wall say to the other wall?",
	"Why did the math book lood sad?",
	"How do you organize a space party?",
	"Why did the bicycle fall over?",
	"What's a vampire's favorite fruit?",
	"How do you catch a squirrel?",
	"Why did the tomato turn red?",
	"What do you call a fish with no eyes?",
	"Why don't oysters donate to charity?",
	"What'js orange and sounds like a parrot?",
	"How does a penguin make pancakes?",
	"Why was the belt arrested?",
	"What did one hat say to the other?",
	"Why did the golfer bring two pairs of pants?",
	"What did the janitor say when he jumped out of the closet?",
	"Why don't scientists trust atoms?",
	"How does a snowman get around?",
	"What do you call a bear with no teeth?",
	"Why don't seagulls fly over the bay?",
	"What do you call a pile of cats?",
	"Why did the cookie go to the doctor?",
	"How do you make a tissue dance?",
	"What did one ocean say to the other ocean?",
	"Why did the computer keep its drink on the windowsill?",
	"What did one plate say to another plate?",
	"Why did the chicken go to the seance?",
	"What did one hat say to another hat?",
	"Why did the golfer bring extra socks?",
	"How do you organize a fantastic space party?",
	"What did the grape do when it got stepped on?",
	"Why did the bicycle fall over?",
	"How do you make a lemon drop?",
	"Why don't skeletons fight each other?",
	"What do you call a fake noodle?",
	"How does a penguin build its house?",
	"What did one wall say to the other wall?",
	"Why did the math book look sad?",
	"How do you organize a space party?",
	"Why did the bicycle fall over?",
	"What's a vampire's favorite fruit?",
	"How do you catch a squirrel?",
	"Why did the tomato turn red?",
	"What do you call a fish with no eyes?",
	"Why don't oysters donate to charity?",
	"What's orange and sounds like a parrot?",
	"How does a penguin make pancakes?"
];