export default [
	"Happy Birthday! 🎂",
	"Happy Teacher's Day! 👨🏻‍🏫",
	"Congratulation on your achievements!",
	"Best wishes for a speedy recovery.",
	"Good luck in your new Job!",
	"Happy anniversary! 🎉",
	"Wishing you success and happiness.",
	"God Bless You",
	"Good Morning!",
	"Good Night",
	"Get well soon!",
	"Happy retirement!",
	"Merry christmas! 🎄",
	"Happy New Year!",
	"Congratulation on the new home! 🏘️",
	"Happy Valentine's Day! 👩🏻‍❤️‍💋‍👨🏻",
	"Wishing you a prosperous Diwali! 🎇",
	"Happy thanksgiving!",
	"Ramdaan Mubarak 🌙",
	"Happy Diwali! 🎇",
	"Eid Mubarak! 🌙",
	"Happy Marry Day! 👰🏻",
	"Congratulation on the graduation! 🎓",
	"Happy Mother's Day! 🤱🏻",
	"Happy Father's Day! 👨🏻",
	"Best wishes on your engagement! 💍",
	"Happy Rose Day! 🥀",
	"Happy Chocolate Day! 🍫"
];